CREATE DATABASE Eshopper;
GO
USE Eshopper;
GO
CREATE TABLE Roles (Id INT IDENTITY PRIMARY KEY, Name NVARCHAR(50) NOT NULL UNIQUE);
CREATE TABLE Users (Id INT IDENTITY PRIMARY KEY, Email NVARCHAR(320) NOT NULL UNIQUE, DisplayName NVARCHAR(120) NOT NULL, PasswordHash NVARCHAR(255) NOT NULL, Role NVARCHAR(50) NOT NULL DEFAULT 'Customer', CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
CREATE TABLE Categories (Id INT IDENTITY PRIMARY KEY, Name NVARCHAR(120) NOT NULL UNIQUE);
CREATE TABLE Products (Id INT IDENTITY PRIMARY KEY, Name NVARCHAR(200) NOT NULL, Description NVARCHAR(MAX) NOT NULL, Price DECIMAL(18,2) NOT NULL, Stock INT NOT NULL, ImageUrl NVARCHAR(500) NOT NULL, IsActive BIT NOT NULL DEFAULT 1, CategoryId INT NOT NULL REFERENCES Categories(Id));
CREATE TABLE Orders (Id INT IDENTITY PRIMARY KEY, UserId INT NOT NULL REFERENCES Users(Id), IdempotencyKey NVARCHAR(120) NOT NULL, Total DECIMAL(18,2) NOT NULL, Status NVARCHAR(40) NOT NULL, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), CONSTRAINT UQ_Orders_User_Idempotency UNIQUE(UserId, IdempotencyKey));
CREATE TABLE OrderItems (Id INT IDENTITY PRIMARY KEY, OrderId INT NOT NULL REFERENCES Orders(Id), ProductId INT NOT NULL REFERENCES Products(Id), ProductName NVARCHAR(200) NOT NULL, UnitPrice DECIMAL(18,2) NOT NULL, Quantity INT NOT NULL);
CREATE TABLE Payments (Id INT IDENTITY PRIMARY KEY, OrderId INT NOT NULL UNIQUE REFERENCES Orders(Id), Amount DECIMAL(18,2) NOT NULL, Status NVARCHAR(40) NOT NULL, TransactionId NVARCHAR(120) NOT NULL, Method NVARCHAR(40) NOT NULL DEFAULT 'card', CardBrand NVARCHAR(40) NOT NULL DEFAULT '', CardLast4 NVARCHAR(4) NOT NULL DEFAULT '', FailureReason NVARCHAR(300) NOT NULL DEFAULT '', ProcessedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), Provider NVARCHAR(40) NOT NULL DEFAULT 'simulated', ProviderOrderId NVARCHAR(120) NOT NULL DEFAULT '', ProviderPaymentId NVARCHAR(120) NOT NULL DEFAULT '', Currency NVARCHAR(10) NOT NULL DEFAULT 'INR', RefundedAmount DECIMAL(18,2) NOT NULL DEFAULT 0, UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
CREATE TABLE AuditActivities (Id INT IDENTITY PRIMARY KEY, UserId INT NULL REFERENCES Users(Id), Action NVARCHAR(120) NOT NULL, Details NVARCHAR(MAX) NOT NULL, IpAddress NVARCHAR(64) NOT NULL DEFAULT '', UserAgent NVARCHAR(300) NOT NULL DEFAULT '', CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
CREATE TABLE PaymentOptions (Code NVARCHAR(40) NOT NULL PRIMARY KEY, Enabled BIT NOT NULL DEFAULT 1);
INSERT INTO PaymentOptions (Code, Enabled) VALUES ('razorpay', 1);
CREATE INDEX IX_AuditActivities_UserId ON AuditActivities(UserId);
CREATE INDEX IX_AuditActivities_Action ON AuditActivities(Action);
CREATE TABLE ShippingAddresses (Id INT IDENTITY PRIMARY KEY, OrderId INT NOT NULL UNIQUE REFERENCES Orders(Id), FullName NVARCHAR(120) NOT NULL, Phone NVARCHAR(20) NOT NULL, Line1 NVARCHAR(200) NOT NULL, Line2 NVARCHAR(200) NOT NULL DEFAULT '', City NVARCHAR(100) NOT NULL, State NVARCHAR(100) NOT NULL, PostalCode NVARCHAR(10) NOT NULL, Country NVARCHAR(100) NOT NULL DEFAULT 'India', Landmark NVARCHAR(200) NOT NULL DEFAULT '');
CREATE TABLE PasswordResetTokens (Id INT IDENTITY PRIMARY KEY, UserId INT NOT NULL REFERENCES Users(Id), TokenHash NVARCHAR(64) NOT NULL, ExpiresAt DATETIME2 NOT NULL, UsedAt DATETIME2 NULL, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
CREATE TABLE SavedAddresses (Id INT IDENTITY PRIMARY KEY, UserId INT NOT NULL REFERENCES Users(Id), FullName NVARCHAR(120) NOT NULL, Phone NVARCHAR(20) NOT NULL, Line1 NVARCHAR(200) NOT NULL, Line2 NVARCHAR(200) NOT NULL DEFAULT '', City NVARCHAR(100) NOT NULL, State NVARCHAR(100) NOT NULL, PostalCode NVARCHAR(10) NOT NULL, Country NVARCHAR(100) NOT NULL DEFAULT 'India', Landmark NVARCHAR(200) NOT NULL DEFAULT '', IsDefault BIT NOT NULL DEFAULT 0, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
-- Product image bytes live in the database so uploads survive restarts and scale across instances.
CREATE TABLE ProductImages (Id INT IDENTITY PRIMARY KEY, FileName NVARCHAR(120) NOT NULL, ContentType NVARCHAR(100) NOT NULL, Content VARBINARY(MAX) NOT NULL, Length BIGINT NOT NULL, UploadedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), UploadedByUserId INT NULL REFERENCES Users(Id));
CREATE INDEX IX_PasswordResetTokens_TokenHash ON PasswordResetTokens(TokenHash);
CREATE INDEX IX_Payments_ProviderOrderId ON Payments(ProviderOrderId);
CREATE INDEX IX_Payments_ProviderPaymentId ON Payments(ProviderPaymentId);
CREATE INDEX IX_SavedAddresses_UserId ON SavedAddresses(UserId);
CREATE TABLE Offers (Id INT IDENTITY PRIMARY KEY, Title NVARCHAR(120) NOT NULL, Description NVARCHAR(1000) NOT NULL DEFAULT '', ImageUrl NVARCHAR(200) NOT NULL, Enabled BIT NOT NULL DEFAULT 1, StartsAt DATETIME2 NOT NULL, EndsAt DATETIME2 NOT NULL, UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), CONSTRAINT CK_Offers_Schedule CHECK (EndsAt > StartsAt));
CREATE INDEX IX_Offers_Enabled_StartsAt_EndsAt ON Offers(Enabled, StartsAt, EndsAt);
CREATE TABLE AppSessions (Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, UserId INT NOT NULL REFERENCES Users(Id) ON DELETE CASCADE, TokenHash NVARCHAR(64) NOT NULL, PasswordStamp NVARCHAR(64) NOT NULL, CreatedAt DATETIME2 NOT NULL, LastRenewedAt DATETIME2 NOT NULL, RevokedAt DATETIME2 NULL);
CREATE UNIQUE INDEX IX_AppSessions_TokenHash ON AppSessions(TokenHash);
CREATE INDEX IX_AppSessions_UserId ON AppSessions(UserId);
CREATE TABLE PushSubscriptions (
    Id INT IDENTITY PRIMARY KEY,
    UserId INT NOT NULL REFERENCES Users(Id) ON DELETE CASCADE,
    AppSessionId UNIQUEIDENTIFIER NULL REFERENCES AppSessions(Id),
    Endpoint NVARCHAR(2048) NOT NULL,
    EndpointHash NVARCHAR(64) NOT NULL,
    P256dh NVARCHAR(87) NOT NULL,
    Auth NVARCHAR(22) NOT NULL,
    LastActivityId INT NOT NULL DEFAULT 0,
    PendingThroughId INT NULL,
    PendingCount INT NOT NULL DEFAULT 0,
    FailureCount INT NOT NULL DEFAULT 0,
    Suspended BIT NOT NULL DEFAULT 0,
    NextAttemptAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    LeaseUntil DATETIME2 NULL,
    Version NVARCHAR(32) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
CREATE UNIQUE INDEX IX_PushSubscriptions_EndpointHash ON PushSubscriptions(EndpointHash);
CREATE INDEX IX_PushSubscriptions_UserId ON PushSubscriptions(UserId);
CREATE INDEX IX_PushSubscriptions_AppSessionId ON PushSubscriptions(AppSessionId);
CREATE INDEX IX_PushSubscriptions_Suspended_NextAttemptAt ON PushSubscriptions(Suspended, NextAttemptAt);
