CREATE DATABASE Eshopper;
GO
USE Eshopper;
GO
CREATE TABLE Roles (Id INT IDENTITY PRIMARY KEY, Name NVARCHAR(50) NOT NULL UNIQUE);
CREATE TABLE Users (Id INT IDENTITY PRIMARY KEY, Email NVARCHAR(320) NOT NULL UNIQUE, DisplayName NVARCHAR(120) NOT NULL, PasswordHash NVARCHAR(255) NOT NULL, Role NVARCHAR(50) NOT NULL DEFAULT 'Customer', CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
CREATE TABLE Categories (Id INT IDENTITY PRIMARY KEY, Name NVARCHAR(120) NOT NULL UNIQUE);
CREATE TABLE Products (Id INT IDENTITY PRIMARY KEY, Name NVARCHAR(200) NOT NULL, Description NVARCHAR(MAX) NOT NULL, Price DECIMAL(18,2) NOT NULL, Stock INT NOT NULL, ImageUrl NVARCHAR(500) NOT NULL, IsActive BIT NOT NULL DEFAULT 1, CategoryId INT NOT NULL REFERENCES Categories(Id));
CREATE TABLE Orders (Id INT IDENTITY PRIMARY KEY, UserId INT NOT NULL REFERENCES Users(Id), IdempotencyKey NVARCHAR(120) NOT NULL, Total DECIMAL(18,2) NOT NULL, Status NVARCHAR(40) NOT NULL, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), CONSTRAINT UQ_Orders_User_Idempotency UNIQUE(UserId, IdempotencyKey));
CREATE TABLE OrderItems (Id INT IDENTITY PRIMARY KEY, OrderId INT NOT NULL REFERENCES Orders(Id), ProductId INT NOT NULL REFERENCES Products(Id), ProductName NVARCHAR(200) NOT NULL, UnitPrice DECIMAL(18,2) NOT NULL, Quantity INT NOT NULL);
CREATE TABLE Payments (Id INT IDENTITY PRIMARY KEY, OrderId INT NOT NULL UNIQUE REFERENCES Orders(Id), Amount DECIMAL(18,2) NOT NULL, Status NVARCHAR(40) NOT NULL, TransactionId NVARCHAR(120) NOT NULL, ProcessedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
CREATE TABLE AuditActivities (Id INT IDENTITY PRIMARY KEY, UserId INT NULL REFERENCES Users(Id), Action NVARCHAR(120) NOT NULL, Details NVARCHAR(MAX) NOT NULL, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
